# Generated by Django 4.2.30 on 2026-04-20 23:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('card_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('points_balance', models.IntegerField(default=0)),
                ('total_earned', models.IntegerField(default=0)),
                ('total_redeemed', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_loyalty_card',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('redemption_ratio', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('min_points_redemption', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_loyalty_program',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POSOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('points_earned', models.IntegerField(default=0)),
                ('points_redeemed', models.IntegerField(default=0)),
                ('invoice_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_invoiced', models.BooleanField(default=False)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('invoiced_by', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cashier_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('loyalty_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.loyaltycard')),
            ],
            options={
                'db_table': 'pos_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True)),
                ('variant_id', models.UUIDField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lot_id', models.UUIDField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.posorder')),
            ],
            options={
                'db_table': 'pos_order_line',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('promo_type', models.CharField(choices=[('percent', 'Percentage Discount'), ('amount', 'Fixed Amount Discount'), ('bogo', 'Buy One Get One'), ('bundle', 'Bundle Discount')], max_length=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('min_qty', models.IntegerField(default=0)),
                ('product_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('free_product_id', models.UUIDField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_promotion',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mpesa', 'M-Pesa'), ('store_credit', 'Store Credit')], max_length=20)),
                ('total_refund', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='pos.posorder')),
            ],
            options={
                'db_table': 'pos_return_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('receipt_header', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_store',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReturnOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField(blank=True)),
                ('original_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.posorderline')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.returnorder')),
            ],
            options={
                'db_table': 'pos_return_order_line',
                'ordering': ['return_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='pos.store')),
            ],
            options={
                'db_table': 'pos_terminal',
                'ordering': ['store', 'name'],
            },
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cashier_id', models.UUIDField(db_index=True)),
                ('state', models.CharField(choices=[('opening', 'Opening'), ('open', 'Open'), ('closing', 'Closing'), ('closed', 'Closed')], default='opening', max_length=20)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pos.posterminal')),
            ],
            options={
                'db_table': 'pos_session',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('loyalty', 'Loyalty Points'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('mpesa_checkout_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.posorder')),
            ],
            options={
                'db_table': 'pos_payment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='posorder',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pos.possession'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='pos.loyaltyprogram'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['corporate_id', 'created_at'], name='pos_order_corpora_a2282b_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['session', 'state'], name='pos_order_session_18a742_idx'),
        ),
    ]
