# Generated by Django 4.2.29 on 2026-03-18 07:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('card_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('points_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_redeemed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('points_per_currency', models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=10)),
                ('redemption_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.01'), help_text='KES value per point', max_digits=10)),
                ('min_points_redemption', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='POSOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('points_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('points_redeemed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('cashier_id', models.UUIDField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('loyalty_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.loyaltycard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.UUIDField()),
                ('variant_id', models.UUIDField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=300)),
                ('sku', models.CharField(blank=True, max_length=150)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('lot_id', models.UUIDField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.posorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('return_number', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('refunded', 'Refunded')], default='draft', max_length=20)),
                ('refund_method', models.CharField(default='cash', max_length=30)),
                ('total_refund', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('processed_by', models.UUIDField(blank=True, null=True)),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.posorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('receipt_header', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('16.0'), help_text='VAT %', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('original_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.posorderline')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.returnorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('promo_type', models.CharField(choices=[('percent_discount', 'Percentage Discount'), ('fixed_discount', 'Fixed Amount Discount'), ('bogo', 'Buy One Get One'), ('bundle', 'Bundle Deal'), ('free_item', 'Free Item')], max_length=30)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('min_qty', models.PositiveIntegerField(default=1)),
                ('product_id', models.UUIDField(blank=True, help_text='Specific product for BOGO/bundle', null=True)),
                ('free_product_id', models.UUIDField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='pos.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='pos.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier_id', models.UUIDField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('closing_control', 'Closing Control'), ('closed', 'Closed')], default='open', max_length=20)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='pos.posterminal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('loyalty_points', 'Loyalty Points'), ('credit', 'Customer Credit'), ('cheque', 'Cheque')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='M-Pesa code, card ref, etc.', max_length=200)),
                ('mpesa_checkout_id', models.CharField(blank=True, max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.posorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='posorder',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos.possession'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='pos.loyaltyprogram'),
        ),
    ]
